services:
  app_web:
    image: app_web
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app_web
    restart: always
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    networks:
      - main_network

networks:
  main_network:
    driver: bridge
