services:
  ts-kai-local:
    image: tailscale/tailscale:latest
    container_name: kai
    hostname: kai
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      - TS_AUTHKEY=${TS_AUTHKEY}
      - TS_SERVE_CONFIG=/config/kai.json
    volumes:
      - ./infra/tailscale/kai-local.json:/config/kai.json
      - ts_kai_local_state:/var/lib/tailscale
    devices:
      - /dev/net/tun:/dev/net/tun
    cap_add:
      - NET_ADMIN
    restart: always

volumes:
  ts_kai_local_state:
