services:
  ts_sidecar:
    image: tailscale/tailscale:latest
    container_name: ts_sidecar
    hostname: kai
    environment:
      - TS_AUTHKEY=${TS_AUTHKEY}
      - TS_STATE_DIR=/var/lib/tailscale
      - TS_SERVE_CONFIG=/config/kai.json
    volumes:
      - ./infra/tailscale/kai.json:/config/kai.json
      - ts_state:/var/lib/tailscale
      - /dev/net/tun:/dev/net/tun
    cap_add:
      - NET_ADMIN
    networks:
      - main_network
    restart: unless-stopped

networks:
  main_network:
    external: true

volumes:
  ts_state:
